Config = {}

Config.framework = "rsg" --"redemrp" or "rsg"

Config.Texts = {
    action = "Action Emotes",
    dance = "Dance Emotes",
    greet = "Greet Emotes",
    reaction = "Reaction Emotes",
    taunt = "Taunt Emotes",
}

Config.Emotes = {
    action = {
        {"Beckon", `KIT_EMOTE_ACTION_BECKON_1`},    
        {"Gold Coin", `KIT_EMOTE_ACTION_BITING_GOLD_COIN_1`},    
        {"Blow Kiss", `KIT_EMOTE_ACTION_BLOW_KISS_1`},    
        {"Boast", `KIT_EMOTE_ACTION_BOAST_1`},
        {"Pocket Watch Check", `KIT_EMOTE_ACTION_CHECK_POCKET_WATCH_1`},    
        {"Coin Flip", `KIT_EMOTE_ACTION_COIN_FLIP_1`},
        {"Fist Pump", `KIT_EMOTE_ACTION_FIST_PUMP_1`},
        {"Flex", `KIT_EMOTE_ACTION_FLEX_1`},
        {"Follow Me", `KIT_EMOTE_ACTION_FOLLOW_ME_1`},
        {"Hissy Fit", `KIT_EMOTE_ACTION_HISSYFIT_1`},
        {"Howl", `KIT_EMOTE_ACTION_HOWL_1`},
        {"Pocket Watch Hypnosis", `KIT_EMOTE_ACTION_HYPNOSIS_POCKET_WATCH_1`},
        {"Lets Craft", `KIT_EMOTE_ACTION_LETS_CRAFT_1`},
        {"Lets Fish", `KIT_EMOTE_ACTION_LETS_FISH_1`},
        {"Lets Go", `KIT_EMOTE_ACTION_LETS_GO_1`},
        {"Play Cards", `KIT_EMOTE_ACTION_LETS_PLAY_CARDS_1`},
        {"Look Distance", `KIT_EMOTE_ACTION_LOOK_DISTANCE_1`},
        {"Yonder", `KIT_EMOTE_ACTION_LOOK_YONDER_1`},
        {"Newthreads", `KIT_EMOTE_ACTION_NEWTHREADS_1`},
        {"Point", `KIT_EMOTE_ACTION_POINT_1`},
        {"Posse Up", `KIT_EMOTE_ACTION_POSSE_UP_1`},
        {"Prayer", `KIT_EMOTE_ACTION_PRAYER_1`},
        {"Prospector Jig", `KIT_EMOTE_ACTION_PROSPECTOR_JIG_1`},
        {"Rock Paper Scissors", `KIT_EMOTE_ACTION_ROCK_PAPER_SCISSORS_1`},
        {"Scheme", `KIT_EMOTE_ACTION_SCHEME_1`},
        {"Shoothip", `KIT_EMOTE_ACTION_SHOOTHIP_1`},
        {"Shooting", `KIT_EMOTE_ACTION_SKYWARD_SHOOTING_1`},
        {"Smoke Cigar", `KIT_EMOTE_ACTION_SMOKE_CIGAR_1`},
        {"Smoke Cigarette", `KIT_EMOTE_ACTION_SMOKE_CIGARETTE_1`},
        {"Action Spit", `KIT_EMOTE_ACTION_SPIT_1`},
        {"Spooky", `KIT_EMOTE_ACTION_SPOOKY_1`},
        {"Stop Here", `KIT_EMOTE_ACTION_STOP_HERE_1`},
        {"Take Notes", `KIT_EMOTE_ACTION_TAKE_NOTES_1`},
    },
    dance = {
        {"Awkward A", `KIT_EMOTE_DANCE_AWKWARD_A_1`},
        {"Carefree A", `KIT_EMOTE_DANCE_CAREFREE_A_1`},
        {"Carefree B", `KIT_EMOTE_DANCE_CAREFREE_B_1`},
        {"Confident A", `KIT_EMOTE_DANCE_CONFIDENT_A_1`},
        {"Confident B", `KIT_EMOTE_DANCE_CONFIDENT_B_1`},
        {"Drunk A", `KIT_EMOTE_DANCE_DRUNK_A_1`},
        {"Drunk B", `KIT_EMOTE_DANCE_DRUNK_B_1`},
        {"Formal A", `KIT_EMOTE_DANCE_FORMAL_A_1`},
        {"Graceful A", `KIT_EMOTE_DANCE_GRACEFUL_A_1`},
        {"Old A", `KIT_EMOTE_DANCE_OLD_A_1`},
        {"Wild A", `KIT_EMOTE_DANCE_WILD_A_1`},
        {"Wild B", `KIT_EMOTE_DANCE_WILD_B_1`},
    },
    greet = {
        {"Finger Salute", `KIT_EMOTE_GREET_FINGER_SALUTE_1`},
        {"Fancy Bow", `KIT_EMOTE_GREET_FANCY_BOW_1`},
        {"Gentlewave", `KIT_EMOTE_GREET_GENTLEWAVE_1`},
        {"Get Over Here", `KIT_EMOTE_GREET_GET_OVER_HERE_1`},
        {"Greet Glad", `KIT_EMOTE_GREET_GLAD_1`},
        {"Hat Flick", `KIT_EMOTE_GREET_HAT_FLICK_1`},
        {"Hat Tip", `KIT_EMOTE_GREET_HAT_TIP_1`},
        {"Hey You", `KIT_EMOTE_GREET_HEY_YOU_1`},
        {"Respectful Bow", `KIT_EMOTE_GREET_RESPECTFUL_BOW_1`},
        {"Seven", `KIT_EMOTE_GREET_SEVEN_1`},
        {"Subtle Wave", `KIT_EMOTE_GREET_SUBTLE_WAVE_1`},
        {"Tada", `KIT_EMOTE_GREET_TADA_1`},
        {"Thumbs Up", `KIT_EMOTE_GREET_THUMBSUP_1`},
        {"Tough", `KIT_EMOTE_GREET_TOUGH_1`},
        {"Wavenear", `KIT_EMOTE_GREET_WAVENEAR_1`},
    },
    reaction = {
        {"Applause", `KIT_EMOTE_REACTION_APPLAUSE_1`},
        {"Begmercy", `KIT_EMOTE_REACTION_BEGMERCY_1`},
        {"Clap Along", `KIT_EMOTE_REACTION_CLAP_ALONG_1`},
        {"Hangover", `KIT_EMOTE_REACTION_HANGOVER_1`},
        {"How Dare you", `KIT_EMOTE_REACTION_HOW_DARE_YOU_1`},
        {"Hurl", `KIT_EMOTE_REACTION_HURL_1`},
        {"Hush your Mouth", `KIT_EMOTE_REACTION_HUSH_YOUR_MOUTH_1`},
        {"Jovial Laugh", `KIT_EMOTE_REACTION_JOVIAL_LAUGH_1`},
        {"Nod Head", `KIT_EMOTE_REACTION_NOD_HEAD_1`},
        {"Point Laugh", `KIT_EMOTE_REACTION_POINTLAUGH_1`},
        {"Scared", `KIT_EMOTE_REACTION_SCARED_1`},
        {"Shake Head", `KIT_EMOTE_REACTION_SHAKEHEAD_1`},
        {"Shot", `KIT_EMOTE_REACTION_SHOT_1`},
        {"Shrug", `KIT_EMOTE_REACTION_SHRUG_1`},
        {"Shuffle", `KIT_EMOTE_REACTION_SHUFFLE_1`},
        {"Slow Clap", `KIT_EMOTE_REACTION_SLOW_CLAP_1`},
        {"Sniffing", `KIT_EMOTE_REACTION_SNIFFING_1`},
        {"Sob", `KIT_EMOTE_REACTION_SOB_1`},
        {"Surrender", `KIT_EMOTE_REACTION_SURRENDER_1`},
        {"Thanks", `KIT_EMOTE_REACTION_THANKS_1`},
        {"Thumbsdown", `KIT_EMOTE_REACTION_THUMBSDOWN_1`},
        {"Who Me", `KIT_EMOTE_REACTION_WHO_ME_1`},
        {"Yeehaw", `KIT_EMOTE_REACTION_YEEHAW_1`},
        {"Okay", `KIT_EMOTE_REACTION_A_OKAY_1`},
    },
    taunt = {
        {"Boohoo", `KIT_EMOTE_TAUNT_BOOHOO_1`}, 
        {"Chicken", `KIT_EMOTE_TAUNT_CHICKEN_1`}, 
        {"Cougar Snarl", `KIT_EMOTE_TAUNT_COUGAR_SNARL_1`}, 
        {"Flip Off", `KIT_EMOTE_TAUNT_FLIP_OFF_1`}, 
        {"Frighten", `KIT_EMOTE_TAUNT_FRIGHTEN_1`}, 
        {"Gorilla Chest", `KIT_EMOTE_TAUNT_GORILLA_CHEST_1`}, 
        {"Im watching you", `KIT_EMOTE_TAUNT_IM_WATCHING_YOU_1`}, 
        {"Provoke", `KIT_EMOTE_TAUNT_PROVOKE_1`}, 
        {"Ripper", `KIT_EMOTE_TAUNT_RIPPER_1`}, 
        {"Throat Slit", `KIT_EMOTE_TAUNT_THROAT_SLIT_1`}, 
        {"Up Yours", `KIT_EMOTE_TAUNT_UP_YOURS_1`}, 
        {"Versus", `KIT_EMOTE_TAUNT_VERSUS_1`}, 
        {"War Cry", `KIT_EMOTE_TAUNT_WAR_CRY_1`}, 
        {"You Stink", `KIT_EMOTE_TAUNT_YOUSTINK_1`}, 
    },
}
