-- * BUY ITEMS * --

-- * TO ADD DECIMAL PRICES TO THE RANDOMPRICE DO IT LIKE THIST math.random(30, 50) / 100 >> this will equal to 0.30 to 0.50 or math.random(300, 500) / 100 will equal to 3.00 to 5.00

-- * THESE ARE JUST EXAMPLES YOU MUST CONFIGURE YOUR OWN STORES *--
Config.BuyItems = {
    Valentine = {

        {
            itemLabel = "Hakke",                  -- Label of the item
            itemName = "pickaxe",                    -- same as in your database
            currencyType = "cash",                   -- cash or gold
            buyprice = 150,                           -- fixed price if randomprices is false in this stores config
            randomprice = math.random(30, 50) / 100, -- random price between 30 and 50 if randomprices is true in this store. adding a /100 the price will be in decimals
            desc = "sell pick axe",                  -- menu description
            category = "tools",                      -- category where this item will show up if set in the store config
            itemLimit = 0,                           -- limit of this item in the store to be sold for  all players
            -- weapon = false,                    -- set to true if you want to sell weapons, or delete this from items
        },
        {
            itemLabel = "Loff",
            itemName = "bread",
            currencyType = "cash",
            buyprice = 1,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Vann",
            itemName = "water",
            currencyType = "cash",
            buyprice = 2,
            randomprice = math.random(15),
            desc = "sell",
            category = "drink",
            itemLimit = 0,
        },
        {
            itemLabel = "Bandasje",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 70,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "tools",
            itemLimit = 0,
        } ,
      {
            itemLabel = "Gulrot",
            itemName = "consumable_carrot",
            currencyType = "cash",
            buyprice = 3,
            randomprice = math.random(30, 45),
            desc = "selg gulrot",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Kjekks",
            itemName = "consumable_crackers",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Kaffekopp med svart kaffe",
            itemName = "consumable_coffee",
            currencyType = "cash",
            buyprice = 6,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "drink",
            itemLimit = 0,
        },
        {
            itemLabel = "Flaske",
            itemName = "bottle",
            currencyType = "cash",
            buyprice = 2,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "drink",
            itemLimit = 0,
        }, 

   },
 ValentineSalonLiten = {

                  {
            itemLabel = "Vann",
            itemName = "water",
            currencyType = "cash",
            buyprice = 2,
            randomprice = math.random(15),
            desc = "Kjøp fjellvann fra Valentine",
            category = "thumbleweedBarDrink",
            itemLimit = 0,
        },
               {
            itemLabel = "Flaske",
            itemName = "bottle",
            currencyType = "cash",
            buyprice = 1,
            randomprice = math.random(30, 45),
            desc = "Tom flaske",
            category = "thumbleweedBarDrink",
            itemLimit = 0,
        }, 
  {
            itemLabel = "Øl",
            itemName = "beer",
            currencyType = "cash",
            buyprice = 4,
            randomprice = math.random(30, 45),
            desc = "ØL ØL OG MERE ØL",
            category = "thumbleweedBarDrink",
            itemLimit = 0,
        }, {
            itemLabel = "Biff og mais",
            itemName = "consumable_cornedbeef_can",
            currencyType = "cash",
            buyprice = 9,
            randomprice = math.random(30, 45),
            desc = "Ny stekt biff med litt mais?",
            category = "thumbleweedBarFood",
            itemLimit = 0,
        }, 



   },
 ValentineSalonStor = {

                  {
            itemLabel = "Vann",
            itemName = "water",
            currencyType = "cash",
            buyprice = 2,
            randomprice = math.random(15),
            desc = "Kjøp fjellvann fra Valentine",
            category = "thumbleweedBarDrink",
            itemLimit = 0,
        },
               {
            itemLabel = "Flaske",
            itemName = "bottle",
            currencyType = "cash",
            buyprice = 1,
            randomprice = math.random(30, 45),
            desc = "Tom flaske",
            category = "thumbleweedBarDrink",
            itemLimit = 0,
        }, 
  {
            itemLabel = "Øl",
            itemName = "beer",
            currencyType = "cash",
            buyprice = 4,
            randomprice = math.random(30, 45),
            desc = "ØL ØL OG MERE ØL",
            category = "thumbleweedBarDrink",
            itemLimit = 0,
        }, {
            itemLabel = "Biff og mais",
            itemName = "consumable_cornedbeef_can",
            currencyType = "cash",
            buyprice = 9,
            randomprice = math.random(30, 45),
            desc = "Ny stekt biff med litt mais?",
            category = "thumbleweedBarFood",
            itemLimit = 0,
        }, 



   },

 ValentineBondensmarked = {

                  {
            itemLabel = "Potetfrø",
            itemName = "potatoseed",
            currencyType = "cash",
            buyprice = 2,
            randomprice = math.random(15),
            desc = "Potetfrø",
            category = "seed",
            itemLimit = 0,
        },
               {
            itemLabel = "Gulrotfrø",
            itemName = "carrotseed",
            currencyType = "cash",
            buyprice = 1,
            randomprice = math.random(30, 45),
            desc = "Gulrotfrø",
            category = "seed",
            itemLimit = 0,
        }, 
  {
            itemLabel = "Marijuanafrø",
            itemName = "marijuanaseed",
            currencyType = "cash",
            buyprice = 4,
            randomprice = math.random(30, 45),
            desc = "Marijuanafrø",
            category = "seed",
            itemLimit = 0,
        }, {
            itemLabel = "Epplefrø",
            itemName = "appleseed",
            currencyType = "cash",
            buyprice = 1,
            randomprice = math.random(30, 45),
            desc = "Epplefrø",
            category = "seed",
            itemLimit = 0,
        },     {
            itemLabel = "Løkpfrø",
            itemName = "onionseed",
            currencyType = "cash",
            buyprice = 2,
            randomprice = math.random(15),
            desc = "Løkfrø",
            category = "seed",
            itemLimit = 0,
        },
               {
            itemLabel = "Bommul",
            itemName = "cottonseed",
            currencyType = "cash",
            buyprice = 3,
            randomprice = math.random(30, 45),
            desc = "Starten på silke",
            category = "seed",
            itemLimit = 0,
        }, 
  {
            itemLabel = "Cocafrø",
            itemName = "cocoaseeds",
            currencyType = "cash",
            buyprice = 3,
            randomprice = math.random(30, 45),
            desc = "Cocafrø, for å lage sjokolade",
            category = "seed",
            itemLimit = 0,
        }, {
            itemLabel = "Sukkerplante frø",
            itemName = "sugarcaneseed",
            currencyType = "cash",
            buyprice = 3,
            randomprice = math.random(30, 45),
            desc = "Sukkerfrø",
            category = "seed",
            itemLimit = 0,
        }, 

{
            itemLabel = "Gjødsel normal",
            itemName = "fertilizer",
            currencyType = "cash",
            buyprice = 1,
            randomprice = math.random(30, 45),
            desc = "Gjødsel",
            category = "fert",
            itemLimit = 0,
        }, {
            itemLabel = "Rake",
            itemName = "hoe",
            currencyType = "cash",
            buyprice = 130,
            randomprice = math.random(30, 45),
            desc = "Rake til å plante",
            category = "tools",
            itemLimit = 0,
        }, 
 {
            itemLabel = "Bøtte",
            itemName = "wateringcan_empty",
            currencyType = "cash",
            buyprice = 50,
            randomprice = math.random(30, 45),
            desc = "Bøtte til vann",
            category = "tools",
            itemLimit = 0,
        }, 

 {
            itemLabel = "Øks",
            itemName = "hatchet",
            currencyType = "cash",
            buyprice = 130,
            randomprice = math.random(30, 45),
            desc = "Øks for å kutte trær",
            category = "tools",
            itemLimit = 0,
        }, 


   },

    Rhodes = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            buyprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },

    Strawberry = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            buyprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },

    Blackwater = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            buyprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    Armadillo = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            buyprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    Tumbleweed = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            buyprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    StDenis = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            buyprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    Vanhorn = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            buyprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    BlackwaterFishing = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            buyprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },

    },
    Wapiti = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            buyprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            buyprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    }
}
